# Generated by Django 4.2.2 on 2023-08-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_rename_telegram_user_linkedin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_notif",
            field=models.BooleanField(default=False),
        ),
    ]
