# Generated by Django 4.2.2 on 2023-08-15 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_remove_user_gender_remove_user_is_video_publisher_and_more"),
        ("blog", "0004_rename_auther_blog_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="age",
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="accounts.user",
                verbose_name="نویسنده مقاله",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="تاریخ آپلود مقاله"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="تاریخ به روز رسانی مقاله"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="accounts.user",
                verbose_name="کاربر",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                ("message", models.TextField()),
                (
                    "blog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifs",
                        to="blog.blog",
                        verbose_name="مقاله",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifs",
                        to="accounts.user",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "خبر",
                "verbose_name_plural": "اخبار",
                "ordering": ("-created_at",),
            },
        ),
    ]
