# Generated by Django 4.1.7 on 2023-10-12 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0007_notification_all_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="favorites",
            field=models.ManyToManyField(
                blank=None,
                default=None,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="favorites",
            ),
        ),
    ]
